### ISSUE TITLE
:bug: Unable to resolve inclusion : #include <ivas/ivas_kernel.h> & <gst/ivas/gstinferencemeta.h>

### ISSUE THREAD

**Issue by lokeshjadhav** [Xilinx/smartcam#1]
:bug: - If you download and try to compile this in Vitis sdk, It gives error at inclusion of the following libraries - **ivas/ivas_kernel.h** & **gst/ivas/gstinferencemeta.h**. For getting this working, I've tried finding the libraries under petalinux rootfs / kernel config. But didn't got it working. Need help in doing so.

**Comment by chkohn** [comment]
@lokeshjadhav please follow the steps here https://xilinx.github.io/kria-apps-docs/master/docs/build_petalinux.html up to and including SDK generation. The generated SDK will provide the IVAS headers and libraries. Make sure you have the application packages enabled as mentioned in the previous section of the docs as that will pull in IVAS and other dependencies.

**Comment by chkohn** [comment]
@lokeshjadhav if this issue is resolved, please close it.
