### ISSUE TITLE
Unable to find vvas/vvas_kernel.h when building the 2022.1 branch for KV260 Ubuntu

### ISSUE THREAD

**Issue by jchua080** [Xilinx/smartcam#6]
I'm building the branch on Ubuntu 20.04.5 and encountered this error. The link https://xilinx.github.io/kria-apps-docs/main/build/html/docs/build_petalinux.html#build-the-sdk provided in the README is broken. Instead, I was using the petalinux sdk from Vitis-AI/setup/mpsoc/host_cross_compiler_setup.sh.

**Comment by ghost** [comment]
@jchua080 hello,my friend, I seem to meet the same error, how did you solve this?

Best regards,

**Comment by jameschua-ep** [comment]
@chihirowhy Hi, I think the reason is because the SDK does not contain VVAS headers and/or libraries. You can try to build VVAS using the SDK, untar VVAS/install/vvas_installer.tar.gz into SDK/sysroots/cortexa72-cortexa53-xilinx-linux and try to rebuild smartcam.
